/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.ProductController.getAllProductByQuery;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import object.Product;
/**
 *
 * @author jocpa
 */
public class CheckStockWindow extends javax.swing.JFrame {

    
    public CheckStockWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableStock = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnConsultarStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TableStock.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableStock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TableStockAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TableStock);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Stock Bodega Anwo");

        btnConsultarStock.setText("Consultar Stock");
        btnConsultarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConsultarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarStock)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableStockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TableStockAncestorAdded
        
        
        
    }//GEN-LAST:event_TableStockAncestorAdded

    private void btnConsultarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarStockActionPerformed
           try {
            

            ArrayList<service.Product> lista  = new ArrayList<>(getAllProduct());

            if (lista.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay datos, verifica tu escritura");
            } else {

                DefaultTableModel modelo = new DefaultTableModel();
                
                modelo.addColumn("Id producto");
                modelo.addColumn("Nombre");
                modelo.addColumn("Marca");
                modelo.addColumn("Modelo");
                modelo.addColumn("Value");
                modelo.addColumn("isAvailable");
               

                for (service.Product item : lista) {

                    Object[] fila = new Object[7]; // le pasamos la cantida de columnas
                    fila[0] = item.getId();
                    fila[1] = item.getName();
                    fila[2] = item.getMark(); 
                    fila[3] = item.getModel();
                    fila[4] = item.getValue();
                    fila[5] = item.getIsAvailable();
                   

                    modelo.addRow(fila);
                 }
            this.TableStock.setModel(modelo);
        }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"No se ha podido cargar la data" +e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnConsultarStockActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            try {
            
            ArrayList<Product> lista = getAllProductByQuery();

            if (lista.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay datos, verifica tu escritura");
            } else {

                DefaultTableModel modelo = new DefaultTableModel();
                
                modelo.addColumn("Id producto");
                modelo.addColumn("Nombre");
                modelo.addColumn("Marca");
                modelo.addColumn("Modelo");
                modelo.addColumn("Value");
                modelo.addColumn("isAvailable");
               

                for (Product item : lista) {

                    Object[] fila = new Object[7]; // le pasamos la cantida de columnas
                    fila[0] = item.getId();
                    fila[1] = item.getName();
                    fila[2] = item.getMark(); 
                    fila[3] = item.getModel();
                    fila[4] = item.getValue();
                    fila[5] = item.getIsAvailable();
                   

                    modelo.addRow(fila);
                 }
            this.TableStock.setModel(modelo);
        }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"No se ha podido cargar la data" +e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckStockWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckStockWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckStockWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckStockWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckStockWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStock;
    private javax.swing.JButton btnConsultarStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<service.Product> getAllProduct() {
        service.ProductService_Service service = new service.ProductService_Service();
        service.ProductService port = service.getProductServicePort();
        return port.getAllProduct();
    }
}
