/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import static controller.ProductController.getAllProductByQuery;
import static controller.ReleaseOrderController.getAllReleaseOrderReportByQuery;
import object.Product;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import object.ReleaseOrderReport;

/**
 *
 * @author jocpa
 */
public class ShippingGuideWindow extends javax.swing.JFrame {

    /**
     * Creates new form ShippingGuideWindows
     */
    public ShippingGuideWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbShippingGuide = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        btnObtenerStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbShippingGuide.setAutoCreateRowSorter(true);
        tbShippingGuide.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro Guia despacho", "Nro Factura", "Cliente", "Producto", "Estado Guia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShippingGuide.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbShippingGuide);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnObtenerStock.setText("Obtener Stock");
        btnObtenerStock.setToolTipText("");
        btnObtenerStock.setAlignmentY(0.0F);
        btnObtenerStock.setAutoscrolls(true);
        btnObtenerStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnObtenerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnImprimir)
                    .addComponent(jScrollPane1))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(btnObtenerStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnImprimir)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObtenerStock)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnObtenerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerStockActionPerformed
    try {
            
            ArrayList<ReleaseOrderReport> lista = getAllReleaseOrderReportByQuery();

            if (lista.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay datos, verifica tu escritura");
            } else {

                DefaultTableModel modelo = new DefaultTableModel();
                modelo.addColumn("Nro Guia Despacho");
                modelo.addColumn("Nro Factura");
                modelo.addColumn("Cliente");
                modelo.addColumn("Producto");
                modelo.addColumn("Estado Guia");
               

                for (ReleaseOrderReport item : lista) {

                    Object[] fila = new Object[7]; // le pasamos la cantida de columnas
                    fila[0] = item.getIdReleaseOrder();
                    fila[1] = item.getIdInvoice();
                    fila[2] = item.getFullNameCustomer();
                    fila[3] = item.getNameProduct();
                    fila[4] = item.getStateReleaseOrder();
                   

                    modelo.addRow(fila);
                 }
            this.tbShippingGuide.setModel(modelo);
        }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"No se ha podido realiza la búsqueda" +e.getMessage());
        }
    }//GEN-LAST:event_btnObtenerStockActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShippingGuideWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShippingGuideWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShippingGuideWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShippingGuideWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShippingGuideWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnObtenerStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbShippingGuide;
    // End of variables declaration//GEN-END:variables
}
